# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbc08b9c925edfa3bb513d12e787917c0243674cf77d24543e7c35dfdd6c4515156377d49cdd8acdf1d176ad52a37f9164f023237ae0f1ee8aae65716fa1e61

test:
  secret_key_base: be57c541a0f87544747d32d833d0d52aff16c306ba8c278ad9b0837f7eb76f0c3463165a0bb5e6823667489900c4f9422b30d4e1e14ee546c5a39f32ce9f7730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
